### ISSUE TITLE
Dependabot not picking up prod dependencies

### ISSUE THREAD

**Issue by lucyb** [ebmdatalab/metrics#108]
Dependabot has been configured to update all prod and dev dependencies weekly. This has been working as expected for development, however we've not been receiving production dependency updates (for example a new version of structlog is available and was updated in Job Server two weeks ago).

The [dependency graph](https://github.com/ebmdatalab/metrics/network/dependencies) shows the dependency is present. I think it might be because we're using a mixture of pyproject.toml and requirements txt files, but it's not obvious why that would be a problem and dependabot runs without error ([logs](https://github.com/ebmdatalab/metrics/network/updates/18219932/jobs)).

https://github.com/ebmdatalab/metrics/blob/84371c12836ce241d322ec4f89895f8716e65f09/.github/dependabot.yml#L4-L8

I tried forking the repo and explicitly mentioning structlog as a dependency in `dependabot.yml`. This successfully produced an (unhelpful) error.
https://github.com/lucyb/ebmdatalab-metrics/network/updates/777871322

```
updater | 2024/01/23 17:27:04 INFO <job_777871322> Checking if structlog 23.2.0 needs updating
  proxy | 2024/01/23 17:27:04 [033] GET https://pypi.org:443/simple/structlog/
  proxy | 2024/01/23 17:27:04 [033] 200 https://pypi.org:443/simple/structlog/
updater | 2024/01/23 17:27:04 INFO <job_777871322> Latest version is 24.1.0
updater | 2024/01/23 17:27:11 INFO <job_777871322> Requirements to unlock own
updater | 2024/01/23 17:27:11 INFO <job_777871322> Requirements update strategy bump_versions
updater | 2024/01/23 17:27:11 INFO <job_777871322> Updating structlog from 23.2.0 to 24.1.0
updater | 2024/01/23 17:27:11 INFO <job_777871322> Sending event f982fdafa3564da2968a0a3e8dc09c2e to Sentry
  proxy | 2024/01/23 17:27:12 [035] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/23 17:27:12 [035] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/23 17:27:12 ERROR <job_777871322> Error processing structlog (RuntimeError)
updater | 2024/01/23 17:27:12 ERROR <job_777871322> No files have changed!
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/python/lib/dependabot/python/file_updater.rb:42:in `updated_dependency_files'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:91:in `generate_dependency_files'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/23 17:27:12 ERROR <job_777871322> bin/update_files.rb:24:in `<main>'
```

**Comment by StevenMaude** [comment]
This was fixed a while ago in #251; closing.
